### ISSUE TITLE
'grunt published-README' was not run in 1.0 branch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#122]
The 1.0 branches of this sim still indicate that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-README` (in master and release branch)

**Comment by pixelzoom** [comment]
This appears to be a problem with `grunt production`.  It runs `grunt published-README` in master, but not in the release branch.

**Comment by jbphet** [comment]
Done.  I'd never thought about doing this, since I figured the README file was mostly viewed on the master branch, but it makes sense that this should be done on the first published branch as well.  @pixelzoom - it there a general issue in chipper or perennial to make the grunt task automatically update the README.md for the first RC branch too?  I looked around but didn't see such an issue.

**Comment by pixelzoom** [comment]
General issue is https://github.com/phetsims/chipper/issues/698.
