### ISSUE TITLE
Replace XYPlotNode with ScrollingChartNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gene-expression-essentials#132]
We would like to remove XYPlotNode and replace with ScrollingChartNode in https://github.com/phetsims/griddle/issues/63. This is the last sim to use the old XYPlotNode, if it can be replaced here it can be removed.

**Comment by jessegreenberg** [comment]
It looks like this plot needs labels along x axis but not y axis, something ScrollingChartNode doesn't support yet.

**Comment by jessegreenberg** [comment]
Replacement was straight forward except that the path for data plotting looks a bit more jagged now:

![image](https://user-images.githubusercontent.com/6396244/92532481-63687a00-f1fe-11ea-8760-7e05173e2dfb.png)

**Comment by jessegreenberg** [comment]
Looks like DynamicSeriesNode needs `lineJoin: round` in the drawing code to look the same.

**Comment by jessegreenberg** [comment]
Done in the above commit. @jbphet would you like to take a look at the change since you are responsible dev?

**Comment by jbphet** [comment]
@jessegreenberg - Thanks for making this update, and the changes look good and the behavior seems correct.  There is one thing that threw me though - it looks like `ProteinLevelChartNode` was changed to use `ScrollingChartNode`, but then `ScrollingChartNode` was renamed to `XYPlotNode` in f381ea2b92f5189ff08f844fb986a8fe39d02157, so if one looks at the code now it looks like the change described in the title of this issue never happened.  It appears that the issue that motivated the change back was https://github.com/phetsims/griddle/issues/71.

This is all fine with me, but I wanted the information recorded here so that it doesn't confuse someone in the future (as it just confused me).  I don't think there is anything left to do here, but I'm going to assign it to @jessegreenberg to make sure that my summary is correct.  @jessegreenberg - if it is, you can just close.

**Comment by jessegreenberg** [comment]
Yes, https://github.com/phetsims/gene-expression-essentials/issues/132#issuecomment-715629080 is a correct summary of the history. Thanks for documenting that, closing.
