### ISSUE TITLE
initial loading of the "Expression" screen takes a long time

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#28]
In requirejs mode, the Expression screen (the first screen) takes a long time to load.  I used a stopwatch and found it to be around 5.5 seconds on my machine, which is long enough that it feels like something is wrong.  We should spend some time profiling an optimizing this.

**Comment by aadish** [comment]
I tried profiling it and my first inclination is that it is because of drawing dna strands on the screen

When DNA strand is drawn on the screen it takes approx 3.5 seconds on my machine
When DNA strand was not rendered on the screen it took less then 60 micro seconds, seems rendering of DNA strand is the cuplrit

**Comment by aadish** [comment]
Current master version takes 40 micro seconds, closing this issue and further performance related issues are tracked in #55
