### ISSUE TITLE
Change sim name simply to "Gene Expression"?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gene-expression-essentials#64]
@phet-steele "Gene Expression Essentials" seems like a complicated name, I feel we could simply call this sim "Gene Expression" since we are unlikely to have a more advanced version or a more basic version.

Since you are now "lead designer" on this sim, what do you think the best name would be? We should settle on one before publication

**Comment by aadish** [comment]
just adding the issue where it was discussed before to form consensus on current name 
https://github.com/phetsims/gene-expression-essentials/issues/8

**Comment by jbphet** [comment]
Bumping to high priority, since this sim is now getting some more attention and will be moving towards a release.

**Comment by phet-steele** [comment]
Using "Gene Expression" for the title:

| Pros | Cons |
| --- | --- |
| Shorter title/Easier to say | Not accurate to the content |
| | Locks us into NEVER creating an advanced version |
| | Extra dev work to change the name |


I believe the sim title is fine as is. In terms of its complexity, we have similarly complicated titles for other sims (imo) so I see no need to change it based on that.

Furthermore, to say we should call it "Gene Expression" simply because we have no plans for a more advanced sim is over dramatic. Gene expression in general is a HUGE topic that has lots of content to teach. Our sim does not exemplify all of gene expression, it only exemplifies the essentials. This sim only makes sense as a generalization of the gene expression process. To call our sim "Gene Expression" would likely cause false perception of what the sim contains. We need a qualifier to better communicate the intent of the sim. To repeat what's already been said in #8:
>I think Gene Expression Essentials conveys that the sim introduces the topic but doesn't provide all of the information as the topic is really complex.

"Gene Expression", on the other hand, does not convey this. We should remain as is.
