### ISSUE TITLE
ribosomes and mRNA destroyers jump to mRNA instead of animating

### ISSUE THREAD

**Issue by jbphet** [phetsims/gene-expression-essentials#91]
On master and on all previously published dev versions, the ribosomes and mRNA destroyers jump to the end of the mRNA strand instead of animating there.  In the Java version, they animate.

**Comment by phet-steele** [comment]
@jbphet see #24 for why this occurs, although it differs from what I requested in https://github.com/phetsims/gene-expression-essentials/issues/24#issuecomment-293010804.

**Comment by ariel-phet** [comment]
@jbphet @phet-steele I cannot say the "jumping" bothers me when user initiated, since it seems to occur in a fairly tight radius to the "ghost cue" highlight. 

It is a bit odd however, when it happens "in the wild" as it does not look physically correct. 

We should ideally make sure the bug in #24 does not occur, but jumping also does not occur if it is not user initiated (if animating all the time is easiest, I am fine with that solution).

**Comment by jbphet** [comment]
I've implemented a solution to this where the destroyers and ribosomes move quickly and directly to attach to the mRNA if the mRNA is in the process of being transcribed, and move in the "meandering" motion toward the mRNA if the mRNA is floating freely.  This looks much better to my eye and doesn't suffer from the problem described in #24.

**Comment by jbphet** [comment]
Unassigning, will have this verified in next dev release.

**Comment by phet-steele** [comment]
Looks great.
